// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.1
// source: llmgateway/v1/completion.proto

// Polyphony LLM Gateway completion contract.
//
// Defines the chat-completion RPC served by the LLM Gateway (Rust) and consumed by
// the Go API server. This is the gRPC counterpart of the REST `POST /completions`
// endpoint (`llm-gateway/src/adapters/inbound/rest/`); both transports share the same
// domain service (`CompletionUseCase`) and must stay semantically identical.
//
// Streaming completions and multimodal (Vision) message content are explicitly out of
// scope for this contract version — see `docs/tasks/step19.md` for the rationale.

package llmgatewaypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Role of a chat message, mirroring the domain `Role` enum
// (`llm-gateway/src/domain/model.rs`).
type ChatRole int32

const (
	// Unset/unknown role. Never produced intentionally; presence indicates a caller bug.
	ChatRole_CHAT_ROLE_UNSPECIFIED ChatRole = 0
	// System instructions / context setting.
	ChatRole_CHAT_ROLE_SYSTEM ChatRole = 1
	// User input.
	ChatRole_CHAT_ROLE_USER ChatRole = 2
	// AI response.
	ChatRole_CHAT_ROLE_ASSISTANT ChatRole = 3
	// Tool execution result (web search, function calls, etc.).
	ChatRole_CHAT_ROLE_TOOL ChatRole = 4
)

// Enum value maps for ChatRole.
var (
	ChatRole_name = map[int32]string{
		0: "CHAT_ROLE_UNSPECIFIED",
		1: "CHAT_ROLE_SYSTEM",
		2: "CHAT_ROLE_USER",
		3: "CHAT_ROLE_ASSISTANT",
		4: "CHAT_ROLE_TOOL",
	}
	ChatRole_value = map[string]int32{
		"CHAT_ROLE_UNSPECIFIED": 0,
		"CHAT_ROLE_SYSTEM":      1,
		"CHAT_ROLE_USER":        2,
		"CHAT_ROLE_ASSISTANT":   3,
		"CHAT_ROLE_TOOL":        4,
	}
)

func (x ChatRole) Enum() *ChatRole {
	p := new(ChatRole)
	*p = x
	return p
}

func (x ChatRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChatRole) Descriptor() protoreflect.EnumDescriptor {
	return file_llmgateway_v1_completion_proto_enumTypes[0].Descriptor()
}

func (ChatRole) Type() protoreflect.EnumType {
	return &file_llmgateway_v1_completion_proto_enumTypes[0]
}

func (x ChatRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChatRole.Descriptor instead.
func (ChatRole) EnumDescriptor() ([]byte, []int) {
	return file_llmgateway_v1_completion_proto_rawDescGZIP(), []int{0}
}

// A single chat message.
//
// `content` is plain text only. Multimodal content parts (images) are not represented
// in this contract version; see the file-level comment.
type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          ChatRole               `protobuf:"varint,1,opt,name=role,proto3,enum=polyphony.llmgateway.v1.ChatRole" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_llmgateway_v1_completion_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_llmgateway_v1_completion_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_llmgateway_v1_completion_proto_rawDescGZIP(), []int{0}
}

func (x *ChatMessage) GetRole() ChatRole {
	if x != nil {
		return x.Role
	}
	return ChatRole_CHAT_ROLE_UNSPECIFIED
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// A chat completion request.
type CompletionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Model identifier to route the request to (e.g. "gpt-5.2").
	Model string `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	// Conversation history, oldest first.
	Messages []*ChatMessage `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	// Sampling temperature. Absent means "use the provider's default".
	Temperature *float32 `protobuf:"fixed32,3,opt,name=temperature,proto3,oneof" json:"temperature,omitempty"`
	// Maximum number of tokens to generate. Absent means "use the provider's default".
	MaxTokens     *uint32 `protobuf:"varint,4,opt,name=max_tokens,json=maxTokens,proto3,oneof" json:"max_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompletionRequest) Reset() {
	*x = CompletionRequest{}
	mi := &file_llmgateway_v1_completion_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompletionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletionRequest) ProtoMessage() {}

func (x *CompletionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llmgateway_v1_completion_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletionRequest.ProtoReflect.Descriptor instead.
func (*CompletionRequest) Descriptor() ([]byte, []int) {
	return file_llmgateway_v1_completion_proto_rawDescGZIP(), []int{1}
}

func (x *CompletionRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CompletionRequest) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *CompletionRequest) GetTemperature() float32 {
	if x != nil && x.Temperature != nil {
		return *x.Temperature
	}
	return 0
}

func (x *CompletionRequest) GetMaxTokens() uint32 {
	if x != nil && x.MaxTokens != nil {
		return *x.MaxTokens
	}
	return 0
}

// A single completion choice returned by the provider.
type Choice struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Index of this choice within `CompletionResponse.choices`.
	Index uint32 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	// The generated message.
	Message *ChatMessage `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Why generation stopped (e.g. "stop", "length").
	FinishReason  string `protobuf:"bytes,3,opt,name=finish_reason,json=finishReason,proto3" json:"finish_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Choice) Reset() {
	*x = Choice{}
	mi := &file_llmgateway_v1_completion_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Choice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Choice) ProtoMessage() {}

func (x *Choice) ProtoReflect() protoreflect.Message {
	mi := &file_llmgateway_v1_completion_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Choice.ProtoReflect.Descriptor instead.
func (*Choice) Descriptor() ([]byte, []int) {
	return file_llmgateway_v1_completion_proto_rawDescGZIP(), []int{2}
}

func (x *Choice) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Choice) GetMessage() *ChatMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *Choice) GetFinishReason() string {
	if x != nil {
		return x.FinishReason
	}
	return ""
}

// Token usage statistics for a completion request/response pair.
type Usage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PromptTokens     uint32                 `protobuf:"varint,1,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens uint32                 `protobuf:"varint,2,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	TotalTokens      uint32                 `protobuf:"varint,3,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Usage) Reset() {
	*x = Usage{}
	mi := &file_llmgateway_v1_completion_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Usage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Usage) ProtoMessage() {}

func (x *Usage) ProtoReflect() protoreflect.Message {
	mi := &file_llmgateway_v1_completion_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Usage.ProtoReflect.Descriptor instead.
func (*Usage) Descriptor() ([]byte, []int) {
	return file_llmgateway_v1_completion_proto_rawDescGZIP(), []int{3}
}

func (x *Usage) GetPromptTokens() uint32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *Usage) GetCompletionTokens() uint32 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *Usage) GetTotalTokens() uint32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

// A chat completion response.
type CompletionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Provider-assigned identifier for this completion.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Model that actually served the request.
	Model         string    `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Choices       []*Choice `protobuf:"bytes,3,rep,name=choices,proto3" json:"choices,omitempty"`
	Usage         *Usage    `protobuf:"bytes,4,opt,name=usage,proto3" json:"usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompletionResponse) Reset() {
	*x = CompletionResponse{}
	mi := &file_llmgateway_v1_completion_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompletionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletionResponse) ProtoMessage() {}

func (x *CompletionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llmgateway_v1_completion_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletionResponse.ProtoReflect.Descriptor instead.
func (*CompletionResponse) Descriptor() ([]byte, []int) {
	return file_llmgateway_v1_completion_proto_rawDescGZIP(), []int{4}
}

func (x *CompletionResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CompletionResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CompletionResponse) GetChoices() []*Choice {
	if x != nil {
		return x.Choices
	}
	return nil
}

func (x *CompletionResponse) GetUsage() *Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

// Request message for `CompletionService.EstimateTokens`. Mirrors
// `CompletionRequest`'s shape minus the sampling parameters (`temperature`,
// `max_tokens`), which are irrelevant to estimation — the gRPC counterpart of
// the REST `POST /tokens/estimate` endpoint's request body.
type TokenEstimateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Model identifier the estimate is computed for (for future model-specific
	// tokenizer tuning; the current heuristic is model-agnostic).
	Model string `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	// Conversation history, oldest first.
	Messages      []*ChatMessage `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenEstimateRequest) Reset() {
	*x = TokenEstimateRequest{}
	mi := &file_llmgateway_v1_completion_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenEstimateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenEstimateRequest) ProtoMessage() {}

func (x *TokenEstimateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llmgateway_v1_completion_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenEstimateRequest.ProtoReflect.Descriptor instead.
func (*TokenEstimateRequest) Descriptor() ([]byte, []int) {
	return file_llmgateway_v1_completion_proto_rawDescGZIP(), []int{5}
}

func (x *TokenEstimateRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *TokenEstimateRequest) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

// Response message for `CompletionService.EstimateTokens`.
//
// `estimated_tokens` is an approximation produced by a character-based
// heuristic, not an exact count from the target model's real tokenizer. It is
// intended for UI meters and rough context-budget checks, not for precise
// billing.
type TokenEstimateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Model identifier the estimate was computed for, echoed back from the
	// request.
	Model string `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	// Approximate token count for the given messages.
	EstimatedTokens uint32 `protobuf:"varint,2,opt,name=estimated_tokens,json=estimatedTokens,proto3" json:"estimated_tokens,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TokenEstimateResponse) Reset() {
	*x = TokenEstimateResponse{}
	mi := &file_llmgateway_v1_completion_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenEstimateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenEstimateResponse) ProtoMessage() {}

func (x *TokenEstimateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llmgateway_v1_completion_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenEstimateResponse.ProtoReflect.Descriptor instead.
func (*TokenEstimateResponse) Descriptor() ([]byte, []int) {
	return file_llmgateway_v1_completion_proto_rawDescGZIP(), []int{6}
}

func (x *TokenEstimateResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *TokenEstimateResponse) GetEstimatedTokens() uint32 {
	if x != nil {
		return x.EstimatedTokens
	}
	return 0
}

var File_llmgateway_v1_completion_proto protoreflect.FileDescriptor

const file_llmgateway_v1_completion_proto_rawDesc = "" +
	"\n" +
	"\x1ellmgateway/v1/completion.proto\x12\x17polyphony.llmgateway.v1\"^\n" +
	"\vChatMessage\x125\n" +
	"\x04role\x18\x01 \x01(\x0e2!.polyphony.llmgateway.v1.ChatRoleR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\xd5\x01\n" +
	"\x11CompletionRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12@\n" +
	"\bmessages\x18\x02 \x03(\v2$.polyphony.llmgateway.v1.ChatMessageR\bmessages\x12%\n" +
	"\vtemperature\x18\x03 \x01(\x02H\x00R\vtemperature\x88\x01\x01\x12\"\n" +
	"\n" +
	"max_tokens\x18\x04 \x01(\rH\x01R\tmaxTokens\x88\x01\x01B\x0e\n" +
	"\f_temperatureB\r\n" +
	"\v_max_tokens\"\x83\x01\n" +
	"\x06Choice\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x12>\n" +
	"\amessage\x18\x02 \x01(\v2$.polyphony.llmgateway.v1.ChatMessageR\amessage\x12#\n" +
	"\rfinish_reason\x18\x03 \x01(\tR\ffinishReason\"|\n" +
	"\x05Usage\x12#\n" +
	"\rprompt_tokens\x18\x01 \x01(\rR\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x02 \x01(\rR\x10completionTokens\x12!\n" +
	"\ftotal_tokens\x18\x03 \x01(\rR\vtotalTokens\"\xab\x01\n" +
	"\x12CompletionResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x129\n" +
	"\achoices\x18\x03 \x03(\v2\x1f.polyphony.llmgateway.v1.ChoiceR\achoices\x124\n" +
	"\x05usage\x18\x04 \x01(\v2\x1e.polyphony.llmgateway.v1.UsageR\x05usage\"n\n" +
	"\x14TokenEstimateRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12@\n" +
	"\bmessages\x18\x02 \x03(\v2$.polyphony.llmgateway.v1.ChatMessageR\bmessages\"X\n" +
	"\x15TokenEstimateResponse\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12)\n" +
	"\x10estimated_tokens\x18\x02 \x01(\rR\x0festimatedTokens*|\n" +
	"\bChatRole\x12\x19\n" +
	"\x15CHAT_ROLE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10CHAT_ROLE_SYSTEM\x10\x01\x12\x12\n" +
	"\x0eCHAT_ROLE_USER\x10\x02\x12\x17\n" +
	"\x13CHAT_ROLE_ASSISTANT\x10\x03\x12\x12\n" +
	"\x0eCHAT_ROLE_TOOL\x10\x042\xe9\x01\n" +
	"\x11CompletionService\x12c\n" +
	"\bComplete\x12*.polyphony.llmgateway.v1.CompletionRequest\x1a+.polyphony.llmgateway.v1.CompletionResponse\x12o\n" +
	"\x0eEstimateTokens\x12-.polyphony.llmgateway.v1.TokenEstimateRequest\x1a..polyphony.llmgateway.v1.TokenEstimateResponseBeZcgithub.com/SHIMA0111/multi-user-ai/server/internal/interface/gateway/grpc/llmgatewaypb;llmgatewaypbb\x06proto3"

var (
	file_llmgateway_v1_completion_proto_rawDescOnce sync.Once
	file_llmgateway_v1_completion_proto_rawDescData []byte
)

func file_llmgateway_v1_completion_proto_rawDescGZIP() []byte {
	file_llmgateway_v1_completion_proto_rawDescOnce.Do(func() {
		file_llmgateway_v1_completion_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_llmgateway_v1_completion_proto_rawDesc), len(file_llmgateway_v1_completion_proto_rawDesc)))
	})
	return file_llmgateway_v1_completion_proto_rawDescData
}

var file_llmgateway_v1_completion_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_llmgateway_v1_completion_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_llmgateway_v1_completion_proto_goTypes = []any{
	(ChatRole)(0),                 // 0: polyphony.llmgateway.v1.ChatRole
	(*ChatMessage)(nil),           // 1: polyphony.llmgateway.v1.ChatMessage
	(*CompletionRequest)(nil),     // 2: polyphony.llmgateway.v1.CompletionRequest
	(*Choice)(nil),                // 3: polyphony.llmgateway.v1.Choice
	(*Usage)(nil),                 // 4: polyphony.llmgateway.v1.Usage
	(*CompletionResponse)(nil),    // 5: polyphony.llmgateway.v1.CompletionResponse
	(*TokenEstimateRequest)(nil),  // 6: polyphony.llmgateway.v1.TokenEstimateRequest
	(*TokenEstimateResponse)(nil), // 7: polyphony.llmgateway.v1.TokenEstimateResponse
}
var file_llmgateway_v1_completion_proto_depIdxs = []int32{
	0, // 0: polyphony.llmgateway.v1.ChatMessage.role:type_name -> polyphony.llmgateway.v1.ChatRole
	1, // 1: polyphony.llmgateway.v1.CompletionRequest.messages:type_name -> polyphony.llmgateway.v1.ChatMessage
	1, // 2: polyphony.llmgateway.v1.Choice.message:type_name -> polyphony.llmgateway.v1.ChatMessage
	3, // 3: polyphony.llmgateway.v1.CompletionResponse.choices:type_name -> polyphony.llmgateway.v1.Choice
	4, // 4: polyphony.llmgateway.v1.CompletionResponse.usage:type_name -> polyphony.llmgateway.v1.Usage
	1, // 5: polyphony.llmgateway.v1.TokenEstimateRequest.messages:type_name -> polyphony.llmgateway.v1.ChatMessage
	2, // 6: polyphony.llmgateway.v1.CompletionService.Complete:input_type -> polyphony.llmgateway.v1.CompletionRequest
	6, // 7: polyphony.llmgateway.v1.CompletionService.EstimateTokens:input_type -> polyphony.llmgateway.v1.TokenEstimateRequest
	5, // 8: polyphony.llmgateway.v1.CompletionService.Complete:output_type -> polyphony.llmgateway.v1.CompletionResponse
	7, // 9: polyphony.llmgateway.v1.CompletionService.EstimateTokens:output_type -> polyphony.llmgateway.v1.TokenEstimateResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_llmgateway_v1_completion_proto_init() }
func file_llmgateway_v1_completion_proto_init() {
	if File_llmgateway_v1_completion_proto != nil {
		return
	}
	file_llmgateway_v1_completion_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_llmgateway_v1_completion_proto_rawDesc), len(file_llmgateway_v1_completion_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_llmgateway_v1_completion_proto_goTypes,
		DependencyIndexes: file_llmgateway_v1_completion_proto_depIdxs,
		EnumInfos:         file_llmgateway_v1_completion_proto_enumTypes,
		MessageInfos:      file_llmgateway_v1_completion_proto_msgTypes,
	}.Build()
	File_llmgateway_v1_completion_proto = out.File
	file_llmgateway_v1_completion_proto_goTypes = nil
	file_llmgateway_v1_completion_proto_depIdxs = nil
}
