// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: llmgateway/v1/completion.proto

// Polyphony LLM Gateway completion contract.
//
// Defines the chat-completion RPC served by the LLM Gateway (Rust) and consumed by
// the Go API server. This is the gRPC counterpart of the REST `POST /completions`
// endpoint (`llm-gateway/src/adapters/inbound/rest/`); both transports share the same
// domain service (`CompletionUseCase`) and must stay semantically identical.
//
// Streaming completions and multimodal (Vision) message content are explicitly out of
// scope for this contract version — see `docs/tasks/step19.md` for the rationale.

package llmgatewaypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CompletionService_Complete_FullMethodName       = "/polyphony.llmgateway.v1.CompletionService/Complete"
	CompletionService_EstimateTokens_FullMethodName = "/polyphony.llmgateway.v1.CompletionService/EstimateTokens"
)

// CompletionServiceClient is the client API for CompletionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Chat-completion RPC service, backed by the same `CompletionUseCase` domain port the
// REST `POST /completions` endpoint uses.
type CompletionServiceClient interface {
	// Executes a single (non-streaming) chat completion.
	Complete(ctx context.Context, in *CompletionRequest, opts ...grpc.CallOption) (*CompletionResponse, error)
	// Returns an approximate token count for a list of chat messages, the gRPC
	// counterpart of the REST `POST /tokens/estimate` endpoint.
	EstimateTokens(ctx context.Context, in *TokenEstimateRequest, opts ...grpc.CallOption) (*TokenEstimateResponse, error)
}

type completionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCompletionServiceClient(cc grpc.ClientConnInterface) CompletionServiceClient {
	return &completionServiceClient{cc}
}

func (c *completionServiceClient) Complete(ctx context.Context, in *CompletionRequest, opts ...grpc.CallOption) (*CompletionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompletionResponse)
	err := c.cc.Invoke(ctx, CompletionService_Complete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *completionServiceClient) EstimateTokens(ctx context.Context, in *TokenEstimateRequest, opts ...grpc.CallOption) (*TokenEstimateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TokenEstimateResponse)
	err := c.cc.Invoke(ctx, CompletionService_EstimateTokens_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CompletionServiceServer is the server API for CompletionService service.
// All implementations must embed UnimplementedCompletionServiceServer
// for forward compatibility.
//
// Chat-completion RPC service, backed by the same `CompletionUseCase` domain port the
// REST `POST /completions` endpoint uses.
type CompletionServiceServer interface {
	// Executes a single (non-streaming) chat completion.
	Complete(context.Context, *CompletionRequest) (*CompletionResponse, error)
	// Returns an approximate token count for a list of chat messages, the gRPC
	// counterpart of the REST `POST /tokens/estimate` endpoint.
	EstimateTokens(context.Context, *TokenEstimateRequest) (*TokenEstimateResponse, error)
	mustEmbedUnimplementedCompletionServiceServer()
}

// UnimplementedCompletionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCompletionServiceServer struct{}

func (UnimplementedCompletionServiceServer) Complete(context.Context, *CompletionRequest) (*CompletionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Complete not implemented")
}
func (UnimplementedCompletionServiceServer) EstimateTokens(context.Context, *TokenEstimateRequest) (*TokenEstimateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EstimateTokens not implemented")
}
func (UnimplementedCompletionServiceServer) mustEmbedUnimplementedCompletionServiceServer() {}
func (UnimplementedCompletionServiceServer) testEmbeddedByValue()                           {}

// UnsafeCompletionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CompletionServiceServer will
// result in compilation errors.
type UnsafeCompletionServiceServer interface {
	mustEmbedUnimplementedCompletionServiceServer()
}

func RegisterCompletionServiceServer(s grpc.ServiceRegistrar, srv CompletionServiceServer) {
	// If the following call pancis, it indicates UnimplementedCompletionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CompletionService_ServiceDesc, srv)
}

func _CompletionService_Complete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompletionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompletionServiceServer).Complete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CompletionService_Complete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompletionServiceServer).Complete(ctx, req.(*CompletionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CompletionService_EstimateTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenEstimateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompletionServiceServer).EstimateTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CompletionService_EstimateTokens_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompletionServiceServer).EstimateTokens(ctx, req.(*TokenEstimateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CompletionService_ServiceDesc is the grpc.ServiceDesc for CompletionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CompletionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "polyphony.llmgateway.v1.CompletionService",
	HandlerType: (*CompletionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Complete",
			Handler:    _CompletionService_Complete_Handler,
		},
		{
			MethodName: "EstimateTokens",
			Handler:    _CompletionService_EstimateTokens_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "llmgateway/v1/completion.proto",
}
