// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.1
// source: llmgateway/v1/models.proto

// Polyphony LLM Gateway model-listing contract.
//
// Defines the model-metadata RPC served by the LLM Gateway (Rust) and consumed by the
// Go API server. This is the gRPC counterpart of the REST `GET /models` endpoint
// (`llm-gateway/src/adapters/inbound/rest/`); both transports share the same domain
// service (`CompletionUseCase`) and must expose identical model metadata.

package llmgatewaypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Per-model pricing, expressed per 1 million tokens.
//
// Per-1M-token USD pricing is the project-wide canonical unit for model pricing,
// matching how OpenAI/Anthropic/Google publish their price lists. Never introduce a
// per-1k-token field alongside this one.
type ModelPricing struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// USD price per 1,000,000 input (prompt) tokens.
	InputPricePerMillionTokens float64 `protobuf:"fixed64,1,opt,name=input_price_per_million_tokens,json=inputPricePerMillionTokens,proto3" json:"input_price_per_million_tokens,omitempty"`
	// USD price per 1,000,000 output (completion) tokens.
	OutputPricePerMillionTokens float64 `protobuf:"fixed64,2,opt,name=output_price_per_million_tokens,json=outputPricePerMillionTokens,proto3" json:"output_price_per_million_tokens,omitempty"`
	// ISO 4217 currency code the prices above are denominated in (e.g. "USD").
	Currency      string `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelPricing) Reset() {
	*x = ModelPricing{}
	mi := &file_llmgateway_v1_models_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelPricing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelPricing) ProtoMessage() {}

func (x *ModelPricing) ProtoReflect() protoreflect.Message {
	mi := &file_llmgateway_v1_models_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelPricing.ProtoReflect.Descriptor instead.
func (*ModelPricing) Descriptor() ([]byte, []int) {
	return file_llmgateway_v1_models_proto_rawDescGZIP(), []int{0}
}

func (x *ModelPricing) GetInputPricePerMillionTokens() float64 {
	if x != nil {
		return x.InputPricePerMillionTokens
	}
	return 0
}

func (x *ModelPricing) GetOutputPricePerMillionTokens() float64 {
	if x != nil {
		return x.OutputPricePerMillionTokens
	}
	return 0
}

func (x *ModelPricing) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

// Information about an available model.
type ModelInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Model identifier used in `CompletionRequest.model` (e.g. "gpt-5.2").
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Human-readable display name (e.g. "GPT-5.2").
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Provider that serves this model (e.g. "openai").
	Provider string `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	// Organization that owns the model (e.g. "openai").
	OwnedBy string `protobuf:"bytes,4,opt,name=owned_by,json=ownedBy,proto3" json:"owned_by,omitempty"`
	// Maximum context window in tokens, if known. Absent means "unknown".
	ContextWindow *uint32 `protobuf:"varint,5,opt,name=context_window,json=contextWindow,proto3,oneof" json:"context_window,omitempty"`
	// Pricing metadata, if known. Absent means "unknown".
	Pricing *ModelPricing `protobuf:"bytes,6,opt,name=pricing,proto3,oneof" json:"pricing,omitempty"`
	// Whether the model accepts image/Vision content parts. Absent means "unknown";
	// consumers must treat an absent value as "no".
	SupportsImageInput *bool `protobuf:"varint,7,opt,name=supports_image_input,json=supportsImageInput,proto3,oneof" json:"supports_image_input,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ModelInfo) Reset() {
	*x = ModelInfo{}
	mi := &file_llmgateway_v1_models_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelInfo) ProtoMessage() {}

func (x *ModelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_llmgateway_v1_models_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelInfo.ProtoReflect.Descriptor instead.
func (*ModelInfo) Descriptor() ([]byte, []int) {
	return file_llmgateway_v1_models_proto_rawDescGZIP(), []int{1}
}

func (x *ModelInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ModelInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModelInfo) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ModelInfo) GetOwnedBy() string {
	if x != nil {
		return x.OwnedBy
	}
	return ""
}

func (x *ModelInfo) GetContextWindow() uint32 {
	if x != nil && x.ContextWindow != nil {
		return *x.ContextWindow
	}
	return 0
}

func (x *ModelInfo) GetPricing() *ModelPricing {
	if x != nil {
		return x.Pricing
	}
	return nil
}

func (x *ModelInfo) GetSupportsImageInput() bool {
	if x != nil && x.SupportsImageInput != nil {
		return *x.SupportsImageInput
	}
	return false
}

// Request message for `ModelsService.ListModels`. Intentionally empty; model listing
// always returns every model across every configured provider.
type ListModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsRequest) Reset() {
	*x = ListModelsRequest{}
	mi := &file_llmgateway_v1_models_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsRequest) ProtoMessage() {}

func (x *ListModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llmgateway_v1_models_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsRequest.ProtoReflect.Descriptor instead.
func (*ListModelsRequest) Descriptor() ([]byte, []int) {
	return file_llmgateway_v1_models_proto_rawDescGZIP(), []int{2}
}

// Response message for `ModelsService.ListModels`.
type ListModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        []*ModelInfo           `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsResponse) Reset() {
	*x = ListModelsResponse{}
	mi := &file_llmgateway_v1_models_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsResponse) ProtoMessage() {}

func (x *ListModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llmgateway_v1_models_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsResponse.ProtoReflect.Descriptor instead.
func (*ListModelsResponse) Descriptor() ([]byte, []int) {
	return file_llmgateway_v1_models_proto_rawDescGZIP(), []int{3}
}

func (x *ListModelsResponse) GetModels() []*ModelInfo {
	if x != nil {
		return x.Models
	}
	return nil
}

var File_llmgateway_v1_models_proto protoreflect.FileDescriptor

const file_llmgateway_v1_models_proto_rawDesc = "" +
	"\n" +
	"\x1allmgateway/v1/models.proto\x12\x17polyphony.llmgateway.v1\"\xb4\x01\n" +
	"\fModelPricing\x12B\n" +
	"\x1einput_price_per_million_tokens\x18\x01 \x01(\x01R\x1ainputPricePerMillionTokens\x12D\n" +
	"\x1foutput_price_per_million_tokens\x18\x02 \x01(\x01R\x1boutputPricePerMillionTokens\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\"\xc7\x02\n" +
	"\tModelInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\x12\x19\n" +
	"\bowned_by\x18\x04 \x01(\tR\aownedBy\x12*\n" +
	"\x0econtext_window\x18\x05 \x01(\rH\x00R\rcontextWindow\x88\x01\x01\x12D\n" +
	"\apricing\x18\x06 \x01(\v2%.polyphony.llmgateway.v1.ModelPricingH\x01R\apricing\x88\x01\x01\x125\n" +
	"\x14supports_image_input\x18\a \x01(\bH\x02R\x12supportsImageInput\x88\x01\x01B\x11\n" +
	"\x0f_context_windowB\n" +
	"\n" +
	"\b_pricingB\x17\n" +
	"\x15_supports_image_input\"\x13\n" +
	"\x11ListModelsRequest\"P\n" +
	"\x12ListModelsResponse\x12:\n" +
	"\x06models\x18\x01 \x03(\v2\".polyphony.llmgateway.v1.ModelInfoR\x06models2v\n" +
	"\rModelsService\x12e\n" +
	"\n" +
	"ListModels\x12*.polyphony.llmgateway.v1.ListModelsRequest\x1a+.polyphony.llmgateway.v1.ListModelsResponseBeZcgithub.com/SHIMA0111/multi-user-ai/server/internal/interface/gateway/grpc/llmgatewaypb;llmgatewaypbb\x06proto3"

var (
	file_llmgateway_v1_models_proto_rawDescOnce sync.Once
	file_llmgateway_v1_models_proto_rawDescData []byte
)

func file_llmgateway_v1_models_proto_rawDescGZIP() []byte {
	file_llmgateway_v1_models_proto_rawDescOnce.Do(func() {
		file_llmgateway_v1_models_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_llmgateway_v1_models_proto_rawDesc), len(file_llmgateway_v1_models_proto_rawDesc)))
	})
	return file_llmgateway_v1_models_proto_rawDescData
}

var file_llmgateway_v1_models_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_llmgateway_v1_models_proto_goTypes = []any{
	(*ModelPricing)(nil),       // 0: polyphony.llmgateway.v1.ModelPricing
	(*ModelInfo)(nil),          // 1: polyphony.llmgateway.v1.ModelInfo
	(*ListModelsRequest)(nil),  // 2: polyphony.llmgateway.v1.ListModelsRequest
	(*ListModelsResponse)(nil), // 3: polyphony.llmgateway.v1.ListModelsResponse
}
var file_llmgateway_v1_models_proto_depIdxs = []int32{
	0, // 0: polyphony.llmgateway.v1.ModelInfo.pricing:type_name -> polyphony.llmgateway.v1.ModelPricing
	1, // 1: polyphony.llmgateway.v1.ListModelsResponse.models:type_name -> polyphony.llmgateway.v1.ModelInfo
	2, // 2: polyphony.llmgateway.v1.ModelsService.ListModels:input_type -> polyphony.llmgateway.v1.ListModelsRequest
	3, // 3: polyphony.llmgateway.v1.ModelsService.ListModels:output_type -> polyphony.llmgateway.v1.ListModelsResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_llmgateway_v1_models_proto_init() }
func file_llmgateway_v1_models_proto_init() {
	if File_llmgateway_v1_models_proto != nil {
		return
	}
	file_llmgateway_v1_models_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_llmgateway_v1_models_proto_rawDesc), len(file_llmgateway_v1_models_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_llmgateway_v1_models_proto_goTypes,
		DependencyIndexes: file_llmgateway_v1_models_proto_depIdxs,
		MessageInfos:      file_llmgateway_v1_models_proto_msgTypes,
	}.Build()
	File_llmgateway_v1_models_proto = out.File
	file_llmgateway_v1_models_proto_goTypes = nil
	file_llmgateway_v1_models_proto_depIdxs = nil
}
