package message

import "time"

// MessageType represents the origin of a message.
type MessageType string

const (
	// MessageTypeHuman is a message sent by a human user.
	MessageTypeHuman MessageType = "human"

	// MessageTypeAI is a message generated by an AI model.
	MessageTypeAI MessageType = "ai"
)

// Message represents a single message in a chat room.
type Message struct {
	ID        string
	RoomID    string
	SenderID  *string // nil for AI messages
	Content   string
	Type      MessageType
	Sequence  int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

// CursorPage holds a page of messages with cursor-based pagination.
type CursorPage struct {
	Messages   []*Message
	NextCursor *string // nil when no more pages
}
