// Package message defines the chat message entity, its repository port, and cursor pagination types.
package message

import "time"

// MessageType represents the origin of a message.
type MessageType string

const (
	// MessageTypeHuman is a message sent by a human user.
	MessageTypeHuman MessageType = "human"

	// MessageTypeAI is a message generated by an AI model.
	MessageTypeAI MessageType = "ai"
)

// MessageStatus represents the delivery status of a message.
type MessageStatus string

const (
	// MessageStatusCompleted indicates the message was delivered successfully.
	MessageStatusCompleted MessageStatus = "completed"

	// MessageStatusFailed indicates the AI call failed. Eligible for regeneration.
	MessageStatusFailed MessageStatus = "failed"
)

// Message represents a single message in a chat room.
type Message struct {
	ID       string
	RoomID   string
	SenderID *string // nil for AI messages
	Content  string
	Type     MessageType
	Status   MessageStatus
	Sequence int64
	// InResponseToMessageID is set on an AI message to the ID of the human
	// message it answers, giving a durable prompt/response link that later
	// context-building/summarization work (Phase 5, 18) can rely on instead
	// of inferring the pairing from adjacent sequence numbers. It is nil for
	// human messages.
	InResponseToMessageID *string
	// IsDeleted marks the message as soft-deleted (see
	// MessageRepository.Delete). A soft-deleted message is excluded from
	// MessageRepository.ListByRoom, MessageRepository.ListByRoomUpTo, and
	// ai.ContextBuilder.Build, but remains fetchable via
	// MessageRepository.GetByID and is never physically removed.
	IsDeleted bool
	// ExcludeFromAI marks the message as excluded from AI context
	// assembly (ai.ContextBuilder.Build) while still appearing in normal
	// room message listings. It lets a user keep a message visible to
	// other humans in the room without it ever being sent to the LLM.
	ExcludeFromAI bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

// CursorPage holds a page of messages with cursor-based pagination.
type CursorPage struct {
	Messages   []*Message
	NextCursor *string // nil when no more pages
}
