package middleware

import (
	"log/slog"
	"time"

	"github.com/labstack/echo/v4"
)

// loggerKey is the Echo context key under which the request-scoped logger is stored.
const loggerKey = "logger"

// RequestLogger returns an Echo middleware that attaches a request-scoped
// *slog.Logger to the Echo context and logs one structured line per request.
// The logger is derived from the given base logger and tagged with the
// request ID generated by echomw.RequestID() (read from the
// X-Request-Id response header, which must already be set by the time this
// middleware runs — register RequestLogger after echomw.RequestID() in the
// middleware chain). Requests that finish with a 5xx status are logged at
// Error level; all others are logged at Info level.
func RequestLogger(logger *slog.Logger) echo.MiddlewareFunc {
	return func(next echo.HandlerFunc) echo.HandlerFunc {
		return func(c echo.Context) error {
			start := time.Now()

			reqID := c.Response().Header().Get(echo.HeaderXRequestID)
			reqLogger := logger.With("request_id", reqID)
			c.Set(loggerKey, reqLogger)

			err := next(c)

			status := c.Response().Status
			duration := time.Since(start)

			if status >= 500 {
				reqLogger.Error("request completed",
					"method", c.Request().Method,
					"path", c.Path(),
					"status", status,
					"duration_ms", duration.Milliseconds(),
				)
			} else {
				reqLogger.Info("request completed",
					"method", c.Request().Method,
					"path", c.Path(),
					"status", status,
					"duration_ms", duration.Milliseconds(),
				)
			}

			return err
		}
	}
}

// GetLogger extracts the request-scoped *slog.Logger stored on the Echo
// context by RequestLogger. It falls back to slog.Default() if no logger was
// set, which happens when RequestLogger was not applied (e.g. unit tests that
// build an Echo context directly). This mirrors the fallback pattern used by
// GetUserID for the authenticated user ID.
func GetLogger(c echo.Context) *slog.Logger {
	logger, ok := c.Get(loggerKey).(*slog.Logger)
	if !ok || logger == nil {
		return slog.Default()
	}
	return logger
}
